export const QUITO_SECTORS = [
  // Parroquias y Sectores Urbanos (Norte)
  'Bellavista',
  'Carcelén',
  'Comité del Pueblo',
  'Concepción',
  'Cochapamba',
  'Cotocollao',
  'El Batán',
  'El Condado',
  'El Inca',
  'González Suárez',
  'Iñaquito (La Carolina)',
  'Jipijapa',
  'Kennedy',
  'La Bota',
  'La Florida',
  'La Luz',
  'La Ofelia',
  'Ponceano',
  'Rumipamba',
  'San Carlos',
  'San Isidro del Inca',

  // Parroquias y Sectores Urbanos (Centro)
  'Belisario Quevedo',
  'Centro Histórico',
  'El Dorado',
  'El Panecillo',
  'El Tejar',
  'Guápulo',
  'Itchimbía',
  'La Floresta',
  'La Gasca',
  'La Libertad',
  'La Mariscal',
  'La Paz',
  'La Vicentina',
  'Las Casas',
  'Miraflores',
  'Monjas',
  'Puengasí',
  'San Juan',
  'San Roque',

  // Parroquias y Sectores Urbanos (Sur)
  'Caupicho',
  'Chilibulo',
  'Chillogallo',
  'Chimbacalle',
  'El Calzado',
  'El Recreo',
  'Guajalo',
  'Guamaní',
  'La Argelia',
  'La Ecuatoriana',
  'La Ferroviaria',
  'La Magdalena',
  'La Mena',
  'Luluncoto',
  'Quitumbe',
  'San Bartolo',
  'Solanda',
  'Turubamba',
  'Villa Flora',

  // Parroquias Rurales y Valles
  'Alangasí',
  'Amaguaña',
  'Atahualpa',
  'Calacalí',
  'Calderón',
  'Carapungo',
  'Chavezpamba',
  'Checa',
  'Conocoto',
  'Cumbayá',
  'El Quinche',
  'Gualea',
  'Guangopolo',
  'Guayllabamba',
  'La Merced',
  'Llano Chico',
  'Llano Grande',
  'Lloa',
  'Nanegal',
  'Nanegalito',
  'Nayón',
  'Nono',
  'Pacto',
  'Perucho',
  'Pifo',
  'Píntag',
  'Pomasqui',
  'Puéllaro',
  'Puembo',
  'San Antonio de Pichincha',
  'San José de Minas',
  'Tababela',
  'Tumbaco',
  'Yaruquí',
  'Zámbiza'
].sort();
